default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: myuser
  password: mypassword
  pool: 5

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test